[env:esp32dev-centralina]
platform = espressif32
board = ESP32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson @ ^7.1.0
  adafruit/RTClib @ ^2.1.4

board_build.filesystem = littlefs
